### ISSUE TITLE
Cargo ficou confuso

### ISSUE THREAD

**Issue by allankildare** [marlon-Symczecym/marlon-Symczecym#1]
Na descrição do seu perfil você colocou que é back-end engineer, mas no README front-end, fiquei um pouco confuso quanto a posição que você assume. Desculpa chegar assim abrindo issue, é uma dúvida mesmo.

**Comment by marlon-Symczecym** [comment]
Olá, capaz, que bom que avisou, já foi mudado, muito obrigado pela pergunta :D
